version: "3.9"
name: "hrpay"

services:
  database:
    image: postgres:16-alpine
    container_name: hrpay-database
    restart: always
    ports:
      - "40432:5432"
    env_file:
        - .env
    volumes:
      - hrpay-database:/var/lib/postgresql/data


volumes:
  hrpay-database:
